services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /var/lib/ratventures:/app/db
    restart: unless-stopped
